### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by VD171** [tfonteyn/Sshd4a#1]
First, thank you very much !
I love your app, this helps alot.

What about to configure a master password ?
And a root mode ?

Regards

_(Solution: For rooted phones, just edit sshd4a code to simple build a binary instead of a library file.
Then, just compile it and run the given sshd4a binary.
Done, sshd4a for rooted phones.)_

**Comment by tfonteyn** [comment]
Thanks you 👍 

> root mode

not going to happen anytime soon; I simply do not have the experience, nor access to enough devices to properly test this.
I'm always open to anyone wanting to provide extra functions of course (pull request, or whatever other way).

> master password

Not sure what you mean? Unless you mean adding support for access with username/password?
I'm not fond of using/maintaining user/pass values.

I've got a background in ssh (from my day-job) and have always favoured using priv/pub keys as they are much more secure.
I admit it's always been a struggle to educate customers (and colleagues ... sigh) to apply proper security.
I often got asked how they (customers) could detect/know who had logged in from where.
This is easy to control with keys, not so good with passwords.
With passwords it's the classic "user writes password on a post-it" security trap which I **really** avoid at all costs. 

Admittedly priv/pub keys take some setting up and I should add such documentation to this project. The basics are fairly simple, but I should add some details on ssh key handling when time permits.

**Comment by VD171** [comment]
For root mode, a simple exec("su") before running the daemon is enough.
And the daemon will then run as uid/gid 0.

For master password, I mean authentication using password and not keys using command line.
(Working as an one user only. So, a master password for a master user (root in this case).)
Examples: 
https://github.com/zcutlip/dropbear-hacks/blob/master/hacks_to_dropbear-2016.74.patch
https://github.com/whit3rabbit/docker-dropbear-password/blob/master/64/dropbear_password.patch
I'm a Fedora Linux user at home for more than 14 years.
I never had a problem with password before.
The password is a problem for those who do not know what they are doing.
A good strong password is enough.

The app should be easy and simple. For risk usage we already have termux as a good option for complex tasks.
I'm using sshdroid for more than 8 years, this app has root mode and master password mode.
Since Android 4.4, Android 5.0, Android 6.0, Android 7.0, Android 8.0, Android 9.0, Android 10.0, Android 11.0 and now, Android 12.0.
But, sshdroid is no longer maintained and is really outdated, so the dropbear binary provides old and deprecated ciphers and key exchange algorithms (diffie-hellman-group1-sha1 and diffie-hellman-group14-sha1).
I tried to build a new dropbear binary, but I'm really bad with ndk :-(

I see Sshd4a as the best solution for replacing sshdroid.
But, I really need root mode and master password mode.

_(Solution: For rooted phones, just edit sshd4a code to simple build a binary instead of a library file.
Then, just compile it and run the given sshd4a binary.
Done, sshd4a for rooted phones.)_

**Comment by tfonteyn** [comment]
>  root mode

ah - I might have misunderstood.

Right now the service does not run as a daemon though :
The SshdService.java code simply does a jni call to the jni-dropbear.c/Java_com_hardbacknutter_sshd_SshdService_start_1sshd
and that does an in-process call to svr-main.c/dropbear_main(...)

Furthermore, access to "su" itself is restricted by Android - I'm not sure it's possible to use it without rooting the device (but, as I mentioned, my experience with rooting android device is near zero)

I'd need to look into this in more detail. I readily admit that my C knowledge is rather "rusty" these days, so this won't happen fast.

> The password is a problem for those who do not know what they are doing.

exactly ! And while you might not be in that group, there are far to many people who are (the tales about customers I have can't be counted/shared...)

PS: Fedora: make sure to check your xz libs :(

**Comment by VD171** [comment]
Nice.
Libsu by topjohnwu is a good option for granting root and checking if it's granted:
https://github.com/topjohnwu/libsu

_(Solution: For rooted phones, just edit sshd4a code to simple build a binary instead of a library file.
Then, just compile it and run the given sshd4a binary.
Done, sshd4a for rooted phones.)_

**Comment by qwn3213** [comment]
To set up password authentication, you can modify lines 58-73 of the [svr-auth.c ](https://github.com/tfonteyn/Sshd4a/blob/dev/app/src/main/cpp/dropbear/svr-auth.c) file to solve the one-time password issue when authorized_keys is not used.
![Snipaste_2024-05-10_16-08-28](https://github.com/tfonteyn/Sshd4a/assets/15106813/c6259cb6-8519-4349-ab72-9d7ece4fd0d5)

**Comment by VD171** [comment]
> To set up password authentication, you can modify lines 58-73 of the [svr-auth.c ](https://github.com/tfonteyn/Sshd4a/blob/dev/app/src/main/cpp/dropbear/svr-auth.c) file to solve the one-time password issue when authorized_keys is not used. 

The problem is how to include the crypt.h file.
I've tried many and many times, but I can't allow usage of crypt() because of the libcrypt.
May you help, please?

_(Solution: For rooted phones, just edit sshd4a code to simple build a binary instead of a library file.
Then, just compile it and run the given sshd4a binary.
Done, sshd4a for rooted phones.)_

**Comment by tfonteyn** [comment]
@qwn3213 : I'm confused. Those lines are not a "problem", they are the solution when not using keys. As I understand the real problem is Android not providing a user/pass system.
But please keep in mind I have very little knowledge in Android user management so I could be wrong.

I think it boils down to providing a 3rd option, i.e.
- keys
- single-use password
- master-password which is independent from the OS, maintained by the Java UI, and checked in a 3rd branch of the dropbear code.

In other words, the "master" password **acts** as a single use-password; 3rd branch with:

    ses.authstate.authtypes = AUTH_TYPE_PASSWORD;
    ses.authstate.pw_passwd = m_strdup(readMasterPasswordFromFileWhichTheUiSaved());

That still does not solve the root-user, but that's separate.

But what I describe above can likely be done.

@VD171 : what do you think of my above proposal?

edit: in addition... add one-way encryption "somehow"
edit2: @VD171 : forgot to answer your question: crypt.h is not available on Android. I think it's going to be a matter of using the bundled libtomcrypt

**Comment by tfonteyn** [comment]
I went ahead and implemented it as described.
Login options will now be:

- keys
- single use password
- master USER and password. In other words, the master-password will be limited to a set user, which can/should be different from the default/device user.

I still need to fiddle with the code to make the UI side easier and fully configurable.
Above all I need to add one-way encryption (hashing) to that master password. 
The latter will mean I need to dig into tomcrypt for an equiv of crypt or maybe just sha2-256), might take some time.

**Comment by tfonteyn** [comment]
and here is [support for the master-user/password](https://github.com/tfonteyn/Sshd4a/releases/tag/v1.2.0)

I'm closing this issue now as I have no short term plans for a root-mode. But it will not be forgotten; I've put it on my "to-investigate" list.

If you have any issues or suggestions with the new version, then of course log a new issue and I'll tackle it.

**Comment by VD171** [comment]
@tfonteyn You are a very good developer and a very good friend !
I really appreciate your care.
Since we have no other choices for running an updated ssh daemon on android, Sshd4a is now our best partner.
Thank you very much and a long and prosperous life to Sshd4a ❤️

_(Solution: For rooted phones, just edit sshd4a code to simple build a binary instead of a library file.
Then, just compile it and run the given sshd4a binary.
Done, sshd4a for rooted phones.)_
