### ISSUE TITLE
No Rsync server provided

### ISSUE THREAD

**Issue by sewnie** [tfonteyn/Sshd4a#10]
The app's description states it provides 'rsync' services, but it has no rsync server included. It would be nice to add it, or to reword the description to 'that can be used with rsync!'

```
$ rsync rsync://android:2222 .
rsync: server sent "SSH-2.0-dropbear_2024.85" rather than greeting
rsync error: error starting client-server protocol (code 5) at main.c(1850) [Receiver=3.3.0]
```

**Comment by tfonteyn** [comment]
urm... please see the project [page](https://github.com/tfonteyn/Sshd4a)

Services are provided by:

    https://rsync.samba.org/    <=====

The latest release contains:

    rsync 3.3.0   <==

Not sure how I can be more clear?

Start ssd4a (presuming device 192.168.0.123, port 2222) and from remote client connect with some variant of the simplest rsync command:

    rsync -vhr -e "ssh -p 2222" someuser@192.168.0.123:/storage/desired/dir  /some/client/dir

More docs:  https://download.samba.org/pub/rsync/rsync.1   check the "usage" section

As to the rsync daemon: nowhere do I state it's included/supported.

**Comment by sewnie** [comment]
I know how to use ssh4da. I am using it and utilizing SSH. The issue i made here is for specifying the rsync daemon support.

> As to the rsync daemon: nowhere do I state it's included/supported.

As the user, I was looking for an app that provides an rsync daemon, and the description of this app is misleading.

> Services are provided by [rsync]

The latest release contains rsync, okay, and for what? The only thing I see being used in the program is Dropbear.

**Comment by tfonteyn** [comment]
I added this text to the project page:

    To be explicitly clear: there is no rsync daemon included. The **services** are all provided via the dropbear port (default 2222).

> The latest release contains rsync, okay, and for what?

for connecting with the rsync client as described. It was in fact the main reason I created the app.

> The only thing I see being used in the program is Dropbear.

dropbear provides the ssh, rsync, sftp services.

hope this clarifies

**Comment by sewnie** [comment]
> for connecting with the rsync client as described.

This is unclear. Rsync is included with the *app* for what reason? Rsync is used to *connect* to the app, from a _different_ device, but why is it included with the app?

> dropbear provides the ssh, rsync, sftp services.

Misleading.

Excerpt from the [Dropbear website](https://matt.ucc.asn.au/dropbear/dropbear.html):
> Dropbear is a relatively small [SSH](https://en.wikipedia.org/wiki/Secure_Shell) server and client.

**Comment by tfonteyn** [comment]
I'm not sure what you are trying to achieve.

Once more in detail:

1. remote ssh-client -> dropbear port -> ssh services provided by dropbear itself
2. remote rsync client -> dropbear port ->rsyn service provided by the bundled rsync from samba
3. remote sftp client -> dropbear port -> sftp service provided by the bundled openssh

Just like ssh and sftp, rsync has a client and a server part. In some cases the rsync server is run as a daemon. As stated this is not the case in this app. The rsync client connects to the dropbear port, which delegates to the samba rsync code.

If you're interested on how its glued together, look at

    https://github.com/tfonteyn/Sshd4a/blob/dev/app/src/main/cpp/jni-dropbear.c

method: exe_to_lib

If you still think this app is misleading, then perhaps this is not the right app for you.
For others and myself, the rsync part works very well and as designed.

**Comment by sewnie** [comment]
> For others and myself, the rsync part works very well and as designed.

**There is no Rsync part.** You can not use the Rsync protocol.

> If you still think this app is misleading

The app is not misleading, it works very great for a SSH server, and is very simple, just the misleading description. I believe there is a misunderstanding.

I understand that the rsync(1) utility can be used with Sshd4a to perform SCP/SFTP, but what i am trying to say is that the rsync protocol is not provided by Sshd4a, aka no rsync daemon. It would be nicer to change the app's description to emphasize usage of the rsync(1) utility over a 'rsync service', which can be mistaken for a rsync _daemon_.

**Comment by tfonteyn** [comment]
> There is no Rsync part. 

Please feel free to edit the above mentioned "jni-dropbear.c" method 'exe_to_lib' removing the rsync "if" lines and the whole rsync sources from cmake file and compile/package the app (it **is** fairly simple to do so) and let me know if your rsync client can still connect. I will certainly be very interested (honestly).

> It would be nicer to change the app's description 
done as per my 2nd original comment

**Comment by sewnie** [comment]
The app works fine. and the Rsync from a machine works, just the app description. Thanks for your time.
