### ISSUE TITLE
Permission question

### ISSUE THREAD

**Issue by IzzySoft** [tfonteyn/Sshd4a#2]
May I ask what `android.permission.REQUEST_INSTALL_PACKAGES` is neeed/used for? And are there some screenshots available? Thanks in advance!

**Comment by tfonteyn** [comment]
The short answer:  I goofed up - ouch...

This is left-over from the application which served as an example (simplesshd, see the link in my readme).
I should have removed it, as it's role was taken over by "android.permission.MANAGE_EXTERNAL_STORAGE"
The error is mine of course.

I'll research to be certain, but I just ran a quick test and it was working fine without.
Thanks for spotting this bug!

I'm in the midst of creating a new version mainly instigated by github #1 
As there are new updates to the external service code, I'm incorporating those as well.
I've got it all running as of only a couple of hours ago, but I now need to test thoroughly of course.

> screenshots 

I'll create the metadata you were so kind to show me, and screenshots, for this project.

Please hold of adding it to your site until done - I'll notify your here when ready.

**Comment by IzzySoft** [comment]
> it's role was taken over by "android.permission.MANAGE_EXTERNAL_STORAGE"

That's a different pair of shoes. `android.permission.MANAGE_EXTERNAL_STORAGE` is needed by e.g. file managers, for full access to "external storage" (including its root and the `Downloads/` directory – all other places are covered by SAF and the special MEDIA permissions). `REQUEST_INSTALL_PACKAGES`, as the name suggests, is only to install packages and thus needed by app managers, app stores etc. So if you do not intent such functionality, it's safe to remove the permission. Glad it was not intended for an integrated self-updater :stuck_out_tongue_winking_eye: So with that permission removed, it allows for being added to the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid) :smiley:

> I'll create the metadata you were so kind to show me, and screenshots, for this project.

I gladly help with that! You're welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for orientation. If you don't want to establish that yourself, you can also make a ZIP with the graphics (screenshots, icon, maybe featureGraphic if you want it) and the short/full description, so I'll create the structures for you and send them via PR.

> Please hold of adding it to your site until done

Oof, I feel caught! I didn't mention this intention before, but of course you are right there :rofl:

> I'll notify your here when ready.

Wonderful, thanks! Looking forward to that then :star_struck:

**Comment by tfonteyn** [comment]
hehe - you forgot we met before.  You've already published my [NeverTooManyBooks](https://github.com/tfonteyn/NeverTooManyBooks) project 💯 

Well, the new 1.2.0 is out now. I've added all the metadata you need I think + screenschots.

That pesky permission is of course removed.

So if you like it, please go ahead and add it to the site. I'll add a link to izzysoft in the readme page when it's up of course!

**Comment by IzzySoft** [comment]
> you forgot we met before

With more than 1.1k apps in the IzzyOnDroid repo (and more having passed through to F-Droid.org), such things can happen unfortunately… :see_no_evil:

> Well, the new 1.2.0 is out now. I've added all the metadata you need I think + screenschots.

Then let's go ahead. Here's what my scanner says:

```
No offending libs found.


Permissions:
------------
* android.permission.INTERNET
* android.permission.RECEIVE_BOOT_COMPLETED
* android.permission.FOREGROUND_SERVICE
* android.permission.FOREGROUND_SERVICE_SPECIAL_USE
* android.permission.POST_NOTIFICATIONS
* android.permission.MANAGE_EXTERNAL_STORAGE
* com.hardbacknutter.sshd.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION

SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

It highlights the storage one – but I guess that can go straight to the app's "green list" (running from shell you'll need `MANAGE_EXTERNAL_STORAGE` to access the storage). However, would be good if you could address the `DEPENDENCY_INFO_BLOCK`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

Looking at the certificate:

```
Number of signers: 1
Signer #1 certificate DN: CN=ca
Signer #1 certificate SHA-256 digest: df971ce7d58d3cdf377c32e0e2f53d6599bd7f130a50c0529c45583ddc12a008
Signer #1 certificate SHA-1 digest: 79be63e6810eae81e9d284a705daa0633a652d0f
Signer #1 certificate MD5 digest: 6537afe8ca9b2ef837ac6d1036d5fd5e
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
```

Not really a deal-breaker, but that DN doesn't really tell much. Who's "ca"? Would be better to have something associating there, e.g. `CN=tfonteyn`. And if you want to reveal as much, the country maybe? Not sure if `EU` is accepted in that field (you could try: `C=EU`). That would then match what your Github profile already states.

If you want to adjust the DN, it should be done before we publish your app (later it would require uninstall/reinstall as the cert will have changed). The dependency blob is fine to be dealt with on the next release then, unless you can tackle it right along. All else looks fine so far (including fastlane) – so I just wait for your decision (and maybe a fresh APK with adjustments, should you have decided for that).

**Comment by tfonteyn** [comment]
> MANAGE_EXTERNAL_STORAGE 

yes, there is no choice, although the user can of course deny the permission. I've done a write-up of this in the new README.md on the project page.

> dependenciesInfo 

interesting, didn't know that - tx! - I've applied this to all my projects now. It'll go into a next release.

>  Who's "ca"?

me, I'm the authority 👹.... 🤣
But seriously, the only reason I sign them is so I can see if a build is mine or someone else, other then that I couldn't care less.

> later it would require uninstall/reinstall

Considering that my other project you published is signed the same way, and that all my projects on github have been signed with this same key, I'd rather leave it as it is. I may not have many users right now, but I don't want to force a reinstall on them.

Sidenote: C=EU is not officially accepted, but in reality you can stick whatever you want in the certificate fields if you self-sign them. I used to sign certs used for internal office use with silly data just to see if anyone would ever notice. In the run of 10+ years only one person bothered checking and finding out 🤭

**Comment by IzzySoft** [comment]
> interesting, didn't know that - tx!

Was kinda sneaked in to some AGP version rather silently IIRC.

> CA

OK – as mentioned, no deal-breaker. Just with a fresh app's first listing, had you wanted to address this, now would have been the best time. So I thought I should mention it at least.

Hm, importing Fastlane gives some warnings on your `full_description.txt`:

```
sanitizeHTML: no scheme specified for 'dropbear', skip setting 'target' and 'rel'.
sanitizeHTML: no scheme specified for 'rsync.samba.org', skip setting 'target' and 'rel'.
sanitizeHTML: no scheme specified for 'openssh', skip setting 'target' and 'rel'.
```

Eh… err: `<li><a href="dropbear">https://matt.ucc.asn.au/dropbear/dropbear.html</a></li>`

That's no Markdown, maybe switch it the other way around? :see_no_evil: Fixed at IzzyOnDroid locally, but you might want to fix it here in your repo as well.

Eh, speaking of which: small typo in the settings screen for "Single use password" – that certainly should be "logon screen", not "log onscreen"? Unless it means one should check the logs on-screen :zany_face:

OK, nuff complained:

![image](https://github.com/tfonteyn/Sshd4a/assets/6781438/3d67978f-5506-40e0-a90e-78ef10177c06)
![image](https://github.com/tfonteyn/Sshd4a/assets/6781438/ead1cb05-fb64-45c5-8ea8-9cd22f1f421e)

And up in the queue of apps I need to check for myself :star_struck: Especially if `rsync -a` is properly supported (setting timestamps correctly). Then I might add a hint and support to my [adbsync](https://codeberg.org/izzy/adbsync) tool as that will probably be faster than my current implementation :stuck_out_tongue_winking_eye:

Should [go live here](https://apt.izzysoft.de/packages/com.hardbacknutter.sshd/) with the next sync around 6 pm UTC then. Rest you know already – badge and all that, right?

**Comment by tfonteyn** [comment]
> full_description.txt

ouch.... how the bleep did I do that? I copy pasted from the github webpage I had open ... oh boy  🤣

>  Unless it means one should check the logs on-screen 🤪

it does in fact, but was missing a space/- character 👍 tx!
The app displays a (minimal) log on the device screen where that single-use password is shown along with login/exit messages.

Both now corrected in the repo. Embarrassing  🙊

> next sync around 6 pm

I'll add the link to your site tomorrow.

> badge and all that

no?

**Comment by IzzySoft** [comment]
> how the bleep did I do that?

:rofl: Happens, as you can see. Always good to have another pair of eyes :smile: 

> but was missing a space/- character

Yupp, looked a bit strange either way.

> Both now corrected in the repo. Embarrassing 🙊

Eh, now – we all make mistakes. That's why bots are much better in solving those captchas :stuck_out_tongue_winking_eye:

>> badge and all that
> no?

Ugh? OK: once the app is listed, be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme. Multiple of them available, including shields if you like. Or both, the shield next to the current "release shield" – and the badge next to the one from Play :wink:

**Comment by tfonteyn** [comment]
badge/link added - closing this issue.

tx!

**Comment by IzzySoft** [comment]
Thank you for writing, providing and maintaining the app! :star_struck:
