### ISSUE TITLE
Permission issue?  Can't copy files.

### ISSUE THREAD

**Issue by famewolf** [tfonteyn/Sshd4a#5]
I am attempting to copy files from one phone to another using sshd4a and a dual pane explorer on linux (krusader).   It does not appear to be letting me write to the storage space.  There is no option to enable root and I've confirmed the only permission (notifications) is granted.  This is on CRDroid 10.5 (Android 14)  

![2024-06-14_22-34](https://github.com/tfonteyn/Sshd4a/assets/4558832/6f1aa7c8-0c1d-464a-8c2c-b2532e3ba98e)

**Comment by tfonteyn** [comment]
> the only permission (notifications) is granted.

Well, this is not the _only_ permission needed. Please see the main project page, where you can find [screen shots](https://github.com/tfonteyn/Sshd4a#android-permissions) on how to enable access to the storage.

**Comment by famewolf** [comment]
Thank you for the reply.  I enabled the popup and I confirmed under all
file access sshd4a is listed as "allowed" on both phones I was trying to
copy from/to.  I can include screen shots if needed.  Any other
possibilities?  (I'm also going to test an alternate app I previously used
named sshdaemon to see if the issue is on my linux side which recently
updated to qt6 and is causing several glitches here and there.)

**Comment by tfonteyn** [comment]
let's start with the basic checks then:

- use a command line and a basic "ssh" command to see if you can access the remote phone.
- have you installed an authorized_keys? or are you using the single-use password; or the master user/password?
- if ssh does not work, start checking the above auth options; i.e. remove (options menu) the current authorized_keys and remove the master user/password.  Then try a simple login using the single-use password.
- Likewise, try the master user/password and/or install a new authorized_keys file.

If plain ssh is working, try command line sftp.

This should eliminate any potential issues with krusader (we can look at that later if needed)

**Comment by famewolf** [comment]
I'm using master user/password.   I got both ssh and sftp on command line to work fine including moving a file and deleting one so looks like the problem is linux/KDE related.  Apologies for wasting your time.  I suspect this is another qt6 issue.  Why they switch to it before they have everything working is beyond me.

**Comment by tfonteyn** [comment]
no worry - always good to know what can go wrong :)

Xfce ❤️

**Comment by famewolf** [comment]
I tested it later with filezilla and sftp worked great so strictly a kde/krusader issue.  Thanks again for the app!

I also like xfce and run it on my older laptop's.  Since lxqt 2.0 was release and is a little "lighter" than xfce I might have to give it a look too.
