### ISSUE TITLE
NOT able to access external USB disk

### ISSUE THREAD

**Issue by sunlin7** [tfonteyn/Sshd4a#7]
I installed the app, and plugin-ed a USB disk to the Android phone, but can NOT access the usb disk, shows the external usb disk path is `/mnt/media_rw/XXXX`.

**Comment by tfonteyn** [comment]
I tried this out with a usb stick and the "My Files" app (samsung) could access it, while sshd4a could NOT.
The stick was formatted as "exFat".

I reformatted it as "FAT32" and tried again. This time sshd4a could access it just fine.

 In theory android can only access "FAT32" and "ext4" partitions, but as I understand different vendors might enhance and/or add dedicated support for others.

Please check your usb disk - other than that, make sure to enable "full file access" as explained on the project page.
Obviously your phone needs to support OTG, but I fully presume you already know that :)

**Comment by sunlin7** [comment]
Hi @tfonteyn 
Resolved by following  your comment, I can access the USB disk now. 
Thank you !
