### ISSUE TITLE
how to use rsync in Android

### ISSUE THREAD

**Issue by pdshw** [tfonteyn/Sshd4a#9]

**Comment by tfonteyn** [comment]
Not much to say/do ..  start the service on your Android device using the desired authentication, see [docs](https://github.com/tfonteyn/Sshd4a/wiki#authentication-methods) and connect from a remote client with an rsync client.

**Comment by pdshw** [comment]
My Android device has no rsync service, Are you saying that I need to install an rsync client on my Android device?
Thanks for your answer

**Comment by tfonteyn** [comment]
Sshd4a (this app) will provide the **server**-side of rsync (and sftp/scp/ssh) on your Android device.

Connecting to it from another device requires an rsync client. Easy to install for Windows/Mac or of course Linux.

If it's your intention to use TWO Android devices... then yes, one of them will need this app to act as the server side, and you will need to install an rsycn client on the second device. **Termux** is a decent terminal app which (I think) brings an rsync client. Perhaps not the easiest if you are not familiar with the rsync command line command though. But take a look around, there are others.

**Comment by pdshw** [comment]
Thank you very much for your help. The problem has been resolved because I used jniLibs.useLegacyPackaging=true in Module, which caused lib/arm64/* *. so file not to be found
Thanks again
